print("Senior Project Developer Profile")
print()
print("Name: Ahmed Mohammed")
print("Major: Computer Science")
print("Technology Interest: Artificial Intelligence")
print("Skill Goal: Full-Stack Web Development")
